CREATE TABLE PERSON
(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    birthdate DATE NOT NULL
);

CREATE SEQUENCE sq_person_id START WITH 1 INCREMENT BY 1;

CREATE TABLE CAR
(
    id NUMBER PRIMARY KEY,
    model VARCHAR2(255) NOT NULL,
    horsepower NUMBER NOT NULL,
    owner_id NUMBER NOT NULL
);

CREATE SEQUENCE sq_car_id START WITH 1 INCREMENT BY 1;