CREATE TABLE PERSON
(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    birthdate TIMESTAMP NOT NULL
);

CREATE TABLE CAR
(
    id NUMBER PRIMARY KEY,
    model VARCHAR2(255) NOT NULL,
    horsepower NUMBER NOT NULL,
    owner_id NUMBER NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE CASCADE
);